### ISSUE TITLE
Failing tests do not cause CI failures

### ISSUE THREAD

**Issue by webmaster128** [frerich/clcache#106]
See https://ci.appveyor.com/project/frerich/clcache/build/job/l9tugke3vgrehcn8

There we have a test failing (testBackslashBeforeQuote) but the CI is still green. There must be some error code missing since the AppVeyor UI change

**Comment by frerich** [comment]
Might well be related to my patch for introducing `py.test`. Maybe it doesn't propagate error codes as expected?

**Comment by webmaster128** [comment]
I assume it is the inline power shell script but I have no clue about power shell.

**Comment by frerich** [comment]
Yes, that may also be the case. Alas, my PowerShell knowledge is fairly limited, too (I took the script code from one of the AppVeyor documentation pages...) so I can't tell right away.

I believe the only reason for using PS in the first place is because it has built-in facilities for uploading files. Otherwise, I'd have just gone for plain batch files.
