### ISSUE TITLE
Commandline parse should use argparse

### ISSUE THREAD

**Issue by YngveNPettersen** [frerich/clcache#269]
The argparse Python module <https://docs.python.org/3/library/argparse.html> should be used to parse the clcache command line.

Using argparse allows for better parsing of the command line and more flexibility, and also allows some conditions, such as registering mutually exclusive arguments. It also automatically creates a --help message.

**Comment by frerich** [comment]
I seem to recall someone tried that a few years ago (that was before Python 3 though) and it didn't actually help very much: the clcache command line API is very small and changes very rarely. Most of the command line handling is actually custom parsing code to replicate the command line parser used by the Microsoft compiler (in order to detect which include directories are used etc.).

I'd be happy to hear that `argparse` became more viable for `clcache`, but I suspect there's not a lot of benefit to reap.

**Comment by YngveNPettersen** [comment]
Argparse makes it easier to add new command line arguments, especially if multiple arguments are can be used. In my case I also needed to add support for specifying the specific cl command to be used

**Comment by frerich** [comment]
Closing this since there still doesn't seem to be a lot of need to change how argument parsing is done. Please don't hesitate to reopen this in case there's a concrete use case.
