### ISSUE TITLE
memcached support

### ISSUE THREAD

**Issue by yoava333** [frerich/clcache#78]
I've been following ccache and there's an upcoming pull request to add support for caching on memcached https://github.com/jrosdahl/ccache/pull/58.
I think it's a great feature to add to clcache.

**Comment by sschuberth** [comment]
The correct link to the memcache PR for ccache is: https://github.com/ccache/ccache/pull/58

**Comment by hubx** [comment]
Hi,

I had a rather straight forward implementation for a rudimentary memcached-only support based on fe83618 . Unfortunately the strategy pattern I applied to ObjectCache is non-trivial to rebase, because there are some parts of the code which are now more tightly coupled to disk access or there have been  new interfaces created which would need to be adapted:

```python
def processCacheHit(cache, objectFile, cachekey):
...
    if os.path.exists(objectFile):
        os.remove(objectFile)
    section = cache.compilerArtifactsRepository.section(cachekey)`
```

I'm happy to take on this task once #160 is finished and no more major logic changes in the cache lookup are expected :)

**Comment by hubx** [comment]
@frerich @yoava333  as #268 is merged, this can be closed?

**Comment by frerich** [comment]
Indeed, I believe this can be closed now. Thanks for bringing this up!
